### ISSUE TITLE
Outdated notarization tool in macOS build script

### ISSUE THREAD

**Issue by RickyRister** [Jojo-Schmitz/MuseScore#293]
The build script for macOS [currently uses](https://github.com/Jojo-Schmitz/MuseScore/blob/3.x/build/ci/macos/notarize.sh#L29) `altool` for notarization. `altool` [stopped working](https://developer.apple.com/news/?id=y5mjxqmn) since November of last year. Apple [suggests](https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool?changes=_3_3) migrating to `notarytool` for notarization.

I suspect this might be the cause of #118

**Comment by Jojo-Schmitz** [comment]
I'll check on this, thanks for the hint.

**Comment by scorster** [comment]
Fingers crossed! I'd love to run the latest builds of MS 3.7 Evolution on my Mac. There have been so many fixes!

And now I think several Piano Roll Editor improvements have been merged.

**Comment by Jojo-Schmitz** [comment]
Hmm, I doubt notarization is an issue at all, as all the builds for this repo and branch are development builds which don't do notarization. They don't do on the upstream repo either, as far as I can tell.

There notarization is done for the upstream nightly builds though, and as this repo and branch here seems to be doing nightly builds too since I marked 3.x the default branch (the workflows CI_Linux, CI_Windows, CI_MacOS), maybe that helps? Currently not though, as there doesn't seem to be any notarization being done, need to check what upstream does differently.

**Comment by Jojo-Schmitz** [comment]
Actually my nigtly build would notarize, if it had `APPLE_USERNAME` and `APPLE_PASSWORD` set
I don't have access to those from the upstream repo though nor do I have some of my own, now would know how to get them :-(

**Comment by RickyRister** [comment]
https://developer.apple.com/support/developer-id/
Unfortunately, seems like you need to sign up for the apple developer program and shell out $99. So probably not a good sign.

**Comment by Jojo-Schmitz** [comment]
$99 per years. Plus the need of an iPhone, iPad or Mac... not going to happen...

**Comment by Jojo-Schmitz** [comment]
What about the PR artifacts for Mu4 on the upstream repo, they are not notarized either (only the nighly builds are), do they work regardless?

**Comment by Jojo-Schmitz** [comment]
Tools updated, even if I can't use them
