### ISSUE TITLE
Mac build doesn't start

### ISSUE THREAD

**Issue by Dmarcus123** [Jojo-Schmitz/MuseScore#698]
The very first time I opened the app, I got the (usual) dialog asking me to grant disk access and I did so.  The app did not open.  When I retried, I see the app icon appear in the task bar for a moment, then it disappears.  

I rebooted, and that made no difference.
I reinstalled, and that made no difference.
I verified that the app has disk access.  It does (bottom app on screen shot).

<img width="469" alt="image" src="https://github.com/user-attachments/assets/3d8ad772-c894-4414-a23e-ed512cb65ae9">

Contents of the package appear fairly normal for an app, and total 368.5mb, fwiw.

What should I do?

THANK YOU.

**Comment by Dmarcus123** [comment]
Any thoughts? I really want to use 3.7!!!

**Comment by Jojo-Schmitz** [comment]
No, sorry

**Comment by Dmarcus123** [comment]
I will try uninstalling and retry with the latest build. I hope I am not
cursed! Hearing about 3.7 was a ray of light.

Dave (he / him)

**Comment by Dmarcus123** [comment]
Sadly (very sadly!), same behavior with MuseScore 3.7.0.11906121159 Nightly.  When started, the app appears in the task bar and bounces exactly once, but does open any window or otherwise open.  It does not appear in the Mac's Force Quit menu - it truly is not running.

**Comment by Jojo-Schmitz** [comment]
I'm affraid I'm lost on this, I donä#t have a Mac nor any special knowledge about them.
Also further problems ar laying ahead: after 3 Dec 2024 I won't be able to build for macOS anymore unless the problems from PR #232 get resolved

**Comment by Jojo-Schmitz** [comment]
Have you seen https://musescore.org/en/node/347226 ? Try the latest (currently builing) artifacts from PR #93

**Comment by Dmarcus123** [comment]
Same behavior,  I’m afraid, using MuseScore 3.7.0.11931942599 Devel.app

**Comment by mkj42** [comment]
I've been chatting with Dave off and on at the facebook 3.7 group
https://www.facebook.com/groups/1013199250562330/?ref=share&mibextid=NSMWBT
He's busy right now, so I offered to ask:
**Could his problems have anything to do with running an iMac with an Intel chip?**
I didn't know how many Mac users you spoke with; I was looking for a common thread.
Pity about after Dec 3, but I'm still curious why he was having problems already.
I haven't even had a Mac for 25 years, and I confess I've read but still don't fully understand the coming changes.

**Comment by Jojo-Schmitz** [comment]
Yes it could. As I don't have any Mac, neither an old nore a nrew, I can't say for sure though.
OTOH, if 3.6.2 runs, 3.7 should do too, although the latter is not notarized, so it is to be expected to jump though some burning hoops

**Comment by mkj42** [comment]
3.6.2 and 4.x do run fine apparently.
You haven't missed much.  We discussed his original problem which was solved and now this new non-starting problem.
Someone suggested starting 3.7 from terminal and looking for errors but apparently there were none.

**Comment by Nockiro** [comment]
Not sure if this might be helpful, but I've been running MacOS builds locally lately (ARM build / M1 SoC) and also had the problem of MuseScore not starting up anymore at some point.  
For me, the culprit somehow seems to be 33f2b198648f5874c1ff499c654b5296e484f5c8 - after that commit, I actually do get a fatal error (when running from Terminal): `Mscore: fatal error: cannot load external font <:/fonts/finalemaestro/FinaleMaestro.otf>`.  
The same message is shown when running the build generated by GitHub Actions (I tried [this one](https://github.com/Jojo-Schmitz/MuseScore/actions/runs/12492006746/)) as far as I can tell.
  
Reverting that commit and building locally I still get a few errors on startup, but nothing that causes MuseScore to crash and those are more likely rooted in my build environment.

**Comment by Jojo-Schmitz** [comment]
@worldwideweary mind to check?

**Comment by Jojo-Schmitz** [comment]
Try starting MuseScore with the -d option

**Comment by worldwideweary** [comment]
Hm, no idea after a quick glance. Wouldn't hurt to revert my commit for your 3.7 though since it's mainly to stop getting an occasional crash that no one else seemed to encounter. Although, it doesn't really make much sense as to why it would affect only FinaleMaestro.otf of all things... so it feels like there's something funny going on more than merely a "generic" error with that commit.

I'm curious as to whether the FinaleMaestro.otf font works on another build for the user with the Mac problem? @Nockiro can you change a score to use Finale Maestro on a working build and have it display fine? (a build after your reverting that commit)

Clearly the exit call here at the bottom:

```cpp
      // Include external and internal score fonts into QFontDatabase
      for (auto& f : _allScoreFonts) {
            QString s(f._fontPath + f._filename);
            if (-1 == QFontDatabase::addApplicationFont(s)) {
                  if (!MScore::testMode)
                        qDebug("Mscore: fatal error: cannot load external font <%s>", qPrintable(s));
                  if (!MScore::debugMode && !MScore::testMode)
                        exit(-1);
                  }
```
is the cause of the program crashing (exit) (apparently !testMode + !debugMode pass through) 

I wonder if converting `exit(-1)` to `return false;` would allow the program to continue as normal after a failure to addApplicationFont (without Finale Maestro), but it remains to be seen wtf is up with the packaged Finale Meastro font  that would trigger Qt library + MacOS to have an issue attempting to add it... I don't receive such an error on my linux device fwiw.

**Comment by Nockiro** [comment]
> I'm curious as to whether the FinaleMaestro.otf font works on another build for the user with the Mac problem? @Nockiro can you change a score to use Finale Maestro on a working build and have it display fine? (a build after your reverting that commit)

So.. I've checked that and this seems to be a bit weird.  
I _am_ able to use the font "Finale Maestro Text", it gets saved and it also gets shown fine in a PDF:
![PDF screenshot with texts in Arial and Finale Maestro Text](https://github.com/user-attachments/assets/55e635d9-cec9-4f15-9742-ab71216ec7a8)

MuseScore 4 also shows this font as an option, but there I also could theoretically choose "Finale Maestro" which I think is what you mean, but that font isn't visible in MuseScore 3.7 to me - so it doesn't work.  
However, it doesn't work in MuseScore 4.4 (4.4.4.243461245) either:
![PDF screenshot with texts in Arial and what should be Finale Maestro](https://github.com/user-attachments/assets/e0b576fc-ebfa-4728-9f81-fdda20945a02)

As to:
> // do not load application specific fonts
// for MAC, they are in Resources/fonts
//
I wonder if this warning may be applicable some how?

It might be. I've had a look at the package contents, the fonts directory in the source code looks vastly different than the end result in the MuseScore 3.7 package (as well as in 4.4), which looks like this:
![image of the MuseScore 3.7 directory, showing only the fonts folder with some of the available fonts](https://github.com/user-attachments/assets/ad20b169-b5ec-41e0-8efa-6d6c96a8f799)

The font I assume you mean (the one stored in FinaleMaestro.otf?) is not included in the 3.7 package.

Also, but I don't know if this has something to do with it, on 3.7 startup via terminal MuseScore explicitly says it hasn't found any fonts - but I don't have anything to compare that with at the moment, so I don't know if that is expected behavior or not:
```
Found 0 user score font   in "/Users/robin/Documents/MuseScore3/Score Fonts" .
Found 0 system score font   in "/Users/robin/Library/Application Support/SMuFL/Fonts" .
Found 0 system score font   in "/Library/Application Support/SMuFL/Fonts" .
```

**Comment by worldwideweary** [comment]
Yes the score font "FinaleMaestro" is to what I'm referring. ... interesting about it not working in 4.4 and in 3.7 when you have a working build. Heck I wonder if maybe others could reproduce the problem using a Mac and 4.x branch. It might even be worth asking on the forums.

Oh, and it definitely (the score font) should be packaged in 3.7:

> The font I assume you mean (the one stored in FinaleMaestro.otf?) is not included in the 3.7 package, as well as a few other fonts (e.g. MuseJazz.otf, Leland.otf etc.)

check for instance /fonts/finalemaestro or online 3.7 @: https://github.com/Jojo-Schmitz/MuseScore/tree/3.x/fonts/finalemaestro

Yeah, I meant the FinaleMaestro.otf referring to your error that somehow Qt is having a problem loading:
>Mscore: fatal error: cannot load external font <:/fonts/finalemaestro/FinaleMaestro.otf>.

I wonder if there's some sort of incompatibility with Finale's font/fonts as they are in their current form and Mac loading fonts via crossplatform Qt libraries. . . but that would definitely be unexpected

**Comment by Nockiro** [comment]
I'm sorry, I changed my post a few times since the original - seems I wasn't quite awake yet 😄 
Changing the notation font to Finale Maestro seems to have an effect in both MuseScore 3.7 and 4.4, sorry for the confusion!

But I did search the whole package for the file FinaleMaestro.otf, it is not included as a separate file - maybe it's somehow packaged in the binary itself, but I don't know MacOS packages enough to know if that would even be possible here.

**Comment by worldwideweary** [comment]
Awake? What's that? Heh. Yeah the FM otf file is an *internal* resource so it's definitely built "into" the program via resource management. It should therefore indisputably manifest as present in the program when being able to change fonts in score preferences:

![image](https://github.com/user-attachments/assets/8901bfee-9a4b-4dc3-b2fe-27e3ec088084)

Sounds like it's working though, which is good.

**Comment by Jojo-Schmitz** [comment]
Try the artifacts from #739 (seems I screwed up on the Mac part when adding Finale Maestro and Finale Broadway to 3.7)

**Comment by mkj42** [comment]
So, does this mean 3.7 is working on Mac more or less?
Has the Dec 3 change been worked out?

**Comment by Jojo-Schmitz** [comment]
Yes, it has, a Christmas present from @cbjeukendrup ?

**Comment by Nockiro** [comment]
> Try the artifacts from #739 (seems I screwed up on the Mac part when adding Finale Maestro and Finale Broadway to 3.7)

The artefact build failed unfortunately, but only for MacOS somehow?

> So, does this mean 3.7 is working on Mac more or less?

At least on my end it seems to be working just fine, yup!
But I've only tested the things I need so far, so I can't confirm whether _everything_ works. 😄

**Comment by Jojo-Schmitz** [comment]
Oops, need to look at that failure, maybe tomorrow

**Comment by Jojo-Schmitz** [comment]
Check again, please, once more @cbjeukendrup saved us...

**Comment by Nockiro** [comment]
Seems to work now, thank you!

**Comment by Dmarcus123** [comment]
Happy to say that 3.7 now loads and run on my Mac!  Thanks Jojo and thanks to all who helped with this.  It seems to have picked up all settings, preferences, recent files, etc. from 3.6.  One question and one problem (I assume these are small things and don't need their own topics/threads.

1. Where do I find release notes?
2. How do I enable play?  The entire toolbar is greyed out ,both on existing scores and on a new one I created. (It works fine in 3.6).

many thanks!

**Comment by Jojo-Schmitz** [comment]
Have you gotten playback to work? (I saw your question about that, before you edited your post)
(and to answer your 2nd question: no, there's ain't real release notes, basically just the Git commit history)

**Comment by Dmarcus123** [comment]
No, but I need to check/fix some things on the Mac relating to the
migration to the new machine and paths. (I was incorrect that 3.6 is
working correctly in playback.

Dave (he / him)
